services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    volumes:
      - ./:/app
  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    volumes:
      - ./:/app

  marimo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marimo
    ports:
      - "8888:8888"
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
    depends_on:
      - spark-master
      - minio
    command: jupyter notebook --ip 0.0.0.0 --port 8888 --allow-root --no-browser --notebook-dir=/app
      
volumes:
  minio-data:
    driver: local